// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	RetCode    int         `json:"ret_code"`
	RetMsg     string      `json:"ret_msg"`
	RetContent interface{} `json:"ret_content"`
}

type LoginReq struct {
	Mode   int64  `json:"mode"`
	Openid string `json:"openid"`
	Phone  string `json:"phone"`
}

type LoginRes struct {
	Uid string `json:"uid"`
}

type UserInfo struct {
	Uid           int64  `json:"uid"`
	Name          string `json:"name"`
	Gender        bool   `json:"gender"`
	Age           int8   `json:"age"`
	Height        int8   `json:"height"`
	Weight        int8   `json:"weight"`
	Birth         string `json:"birth"`
	Constellation string `json:"constellation"` // 星座
	Profession    string `json:"profession"`
	Company       bool   `json:"company"`
	Education     int8   `json:"education"`
	University    int8   `json:"university"`
	HomeProvince  string `json:"homeProvince"`
	HomeCity      string `json:"homeCity"`
	NowProvince   string `json:"nowProvince"`
	NowCity       string `json:"nowCity"`
	Phone         string `json:"phone"`
	Cover         string `json:"cover"`
}
