// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sysuser "github.com/blakeyi/gan-circle-server/api/internal/handler/sys/user"
	"github.com/blakeyi/gan-circle-server/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/sys/user/login",
				Handler: sysuser.UserLoginHandler(serverCtx),
			},
		},
	)
}
